# Wrangler Configuration for Cloudflare Pages
name = "quicktrack"
compatibility_date = "2024-12-26"

# Build configuration for Cloudflare Pages
[build]
command = "bun run build"
cwd = "."
watch_dir = "src"

# Environment Variables (configured via Cloudflare Pages dashboard)
[vars]
NODE_ENV = "production" 