# Wrangler Configuration for Cloudflare Pages/Workers
name = "certrack"
main = ".svelte-kit/output/server/index.js"
compatibility_date = "2024-12-26"
compatibility_flags = ["nodejs_compat"]

# Static Assets Configuration  
[assets]
directory = ".svelte-kit/output/client"
binding = "ASSETS"

# Uncomment and configure when ready to deploy
# account_id = "your-account-id"

# Build configuration for Cloudflare Pages
[build]
command = "bun run build"
cwd = "."
watch_dir = "src"

# Remove pages_build_output_dir to let Cloudflare auto-detect

# Environment Variables
[vars]
# Add your environment variables here
# NOTE: These should be set via Cloudflare dashboard or wrangler secrets
# PUBLIC_SUPABASE_URL = "your-supabase-url"
# PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"

# Development environment
[env.development.vars]
NODE_ENV = "development"

# Production environment  
[env.production.vars]
NODE_ENV = "production"

# KV Namespaces (uncomment when needed)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 Database (uncomment when needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "certrack-db"
# database_id = "your-database-id"

# Durable Objects (uncomment when needed)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

# R2 Bucket (uncomment when needed)
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "certrack-files"

# Routes for custom domains (uncomment when ready)
# routes = [
#   { pattern = "certrack.com/*", zone_name = "certrack.com" },
#   { pattern = "www.certrack.com/*", zone_name = "certrack.com" }
# ]

# Worker limits
[limits]
cpu_ms = 50000 